{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trpc-agent-service.serviceAccountName" . }}
  labels:
    {{- include "trpc-agent-service.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
