-- PostgreSQL 16 reference schema for the multi-tenant Agent platform.
-- Apply schema.sql, then rls.sql. Identifiers are generated by the application so
-- deterministic Inbox, execution, Tool, and delivery IDs survive process crashes.

CREATE TABLE tenant (
    tenant_id          text PRIMARY KEY,
    display_name       text NOT NULL,
    status             text NOT NULL CHECK (status IN ('active', 'suspended', 'deleted')),
    audit_policy       jsonb NOT NULL DEFAULT '{}'::jsonb,
    budget_policy      jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

-- Minimal scheduler index: it deliberately contains only a tenant identifier
-- and enable bit, never tenant business data. Dispatchers enumerate this table
-- before opening one RLS-scoped transaction per tenant.
CREATE TABLE tenant_locator (
    tenant_id          text PRIMARY KEY REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    enabled            boolean NOT NULL DEFAULT true,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE tenant_runtime_state (
    tenant_id          text PRIMARY KEY REFERENCES tenant(tenant_id),
    routing_epoch      bigint NOT NULL DEFAULT 1 CHECK (routing_epoch > 0),
    security_epoch     bigint NOT NULL DEFAULT 1 CHECK (security_epoch > 0),
    credential_revocation_epoch bigint NOT NULL DEFAULT 1,
    execution_mode     text NOT NULL DEFAULT 'normal'
                         CHECK (execution_mode IN ('normal', 'draining', 'suspended', 'emergency_stop')),
    tool_denylist      jsonb NOT NULL DEFAULT '[]'::jsonb,
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE storage_route (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    routing_epoch      bigint NOT NULL,
    profile            jsonb NOT NULL,
    -- The route state machine preserves one writer while a tenant moves between
    -- storage profiles.  `active` is the only writable route; the remaining
    -- values make an interrupted migration observable and recoverable.
    route_status       text NOT NULL CHECK (route_status IN (
                           'preparing', 'backfilling', 'catching_up', 'draining',
                           'verifying', 'active', 'readonly', 'retired', 'failed'
                       )),
    source_watermark   text,
    target_watermark   text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    activated_at       timestamptz,
    PRIMARY KEY (tenant_id, routing_epoch),
    FOREIGN KEY (tenant_id) REFERENCES tenant_runtime_state(tenant_id)
);

CREATE UNIQUE INDEX storage_route_one_active_idx
    ON storage_route (tenant_id) WHERE route_status = 'active';

-- Durable, operator-visible state machine for a tenant storage move.  The
-- active writer remains ``storage_route``; this ledger makes interrupted
-- backfill, drain, verification, and rollback work resumable after restarts.
CREATE TABLE storage_migration (
    tenant_id             text NOT NULL REFERENCES tenant(tenant_id),
    migration_id          text NOT NULL,
    source_profile        jsonb NOT NULL,
    target_profile        jsonb NOT NULL,
    status                text NOT NULL CHECK (status IN (
                              'preparing', 'backfilling', 'catching_up', 'draining',
                              'verifying', 'active', 'readonly', 'retired', 'failed'
                          )),
    source_routing_epoch  bigint NOT NULL,
    target_routing_epoch  bigint,
    source_watermark      text,
    target_watermark      text,
    error                 text,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, migration_id)
);

CREATE INDEX storage_migration_active_idx
    ON storage_migration (tenant_id, updated_at DESC)
    WHERE status IN ('preparing', 'backfilling', 'catching_up', 'draining', 'verifying', 'readonly');

ALTER TABLE tenant_runtime_state
    ADD CONSTRAINT tenant_runtime_active_route_fk
    FOREIGN KEY (tenant_id, routing_epoch)
    REFERENCES storage_route(tenant_id, routing_epoch)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE agent_app (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    agent_id           text NOT NULL,
    name               text NOT NULL,
    status             text NOT NULL CHECK (status IN ('draft', 'active', 'disabled')),
    active_config_version bigint,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, agent_id)
);

CREATE TABLE agent_release (
    tenant_id          text NOT NULL,
    agent_id           text NOT NULL,
    config_version     bigint NOT NULL,
    release_status     text NOT NULL CHECK (release_status IN ('staged', 'active', 'retired')),
    app_config         jsonb NOT NULL DEFAULT '{}'::jsonb,
    model_config       jsonb NOT NULL DEFAULT '{}'::jsonb,
    tool_policy        jsonb NOT NULL DEFAULT '{}'::jsonb,
    knowledge_config   jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by         text NOT NULL,
    change_reason      text NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, agent_id, config_version),
    FOREIGN KEY (tenant_id, agent_id) REFERENCES agent_app(tenant_id, agent_id)
);

ALTER TABLE agent_app
    ADD CONSTRAINT agent_app_active_release_fk
    FOREIGN KEY (tenant_id, agent_id, active_config_version)
    REFERENCES agent_release(tenant_id, agent_id, config_version);

CREATE TABLE channel_binding (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    binding_id         text NOT NULL,
    agent_id           text NOT NULL,
    provider           text NOT NULL,
    external_account_id text NOT NULL,
    webhook_key_hash   text NOT NULL,
    secret_ref         text NOT NULL,
    capabilities       jsonb NOT NULL DEFAULT '{}'::jsonb,
    status             text NOT NULL CHECK (status IN ('active', 'rotating', 'disabled')),
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, binding_id),
    FOREIGN KEY (tenant_id, agent_id) REFERENCES agent_app(tenant_id, agent_id),
    UNIQUE (provider, external_account_id),
    UNIQUE (webhook_key_hash),
    UNIQUE (tenant_id, binding_id, webhook_key_hash)
);

-- Minimal bootstrap index for resolving a tenant before RLS context exists.
-- It has no application table grants; rls.sql exposes exact-match lookup only.
CREATE TABLE channel_binding_locator (
    webhook_key_hash   text PRIMARY KEY,
    resolved_tenant_id text NOT NULL,
    binding_id         text NOT NULL,
    provider           text NOT NULL,
    enabled            boolean NOT NULL DEFAULT true,
    FOREIGN KEY (resolved_tenant_id, binding_id, webhook_key_hash)
        REFERENCES channel_binding(tenant_id, binding_id, webhook_key_hash)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE identity_mapping (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    provider           text NOT NULL,
    external_account_id text NOT NULL,
    external_user_id   text NOT NULL,
    subject_id         text NOT NULL,
    attributes         jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, provider, external_account_id, external_user_id),
    UNIQUE (tenant_id, subject_id, provider, external_account_id, external_user_id)
);

CREATE TABLE session (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    session_id         text NOT NULL,
    agent_id           text NOT NULL,
    channel_binding_id text NOT NULL,
    conversation_type  text NOT NULL CHECK (conversation_type IN ('direct', 'group')),
    conversation_key_hash text NOT NULL,
    id_rule_version    integer NOT NULL DEFAULT 1,
    config_version     bigint NOT NULL,
    state              jsonb NOT NULL DEFAULT '{}'::jsonb,
    version            bigint NOT NULL DEFAULT 0,
    last_event_seq     bigint NOT NULL DEFAULT 0,
    active_inbox_id    text,
    lease_owner        text,
    lease_expires_at   timestamptz,
    lease_fence        bigint NOT NULL DEFAULT 0 CHECK (lease_fence >= 0),
    status             text NOT NULL DEFAULT 'active',
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, session_id),
    FOREIGN KEY (tenant_id, agent_id) REFERENCES agent_app(tenant_id, agent_id),
    FOREIGN KEY (tenant_id, agent_id, config_version)
        REFERENCES agent_release(tenant_id, agent_id, config_version),
    FOREIGN KEY (tenant_id, channel_binding_id) REFERENCES channel_binding(tenant_id, binding_id),
    CHECK (
        (active_inbox_id IS NULL AND lease_owner IS NULL AND lease_expires_at IS NULL)
        OR
        (active_inbox_id IS NOT NULL AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
    )
);

CREATE INDEX session_agent_updated_idx
    ON session (tenant_id, agent_id, updated_at DESC);

CREATE TABLE session_event (
    tenant_id          text NOT NULL,
    session_id         text NOT NULL,
    seq                bigint NOT NULL,
    event_id           text NOT NULL,
    event_type         text NOT NULL,
    role               text,
    subject_id         text,
    external_message_id text,
    payload            jsonb NOT NULL,
    trace_id           text NOT NULL,
    occurred_at        timestamptz NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, session_id, seq),
    UNIQUE (tenant_id, event_id),
    FOREIGN KEY (tenant_id, session_id) REFERENCES session(tenant_id, session_id)
);

CREATE INDEX session_event_trace_idx ON session_event (tenant_id, trace_id);

CREATE TABLE session_summary (
    tenant_id          text NOT NULL,
    session_id         text NOT NULL,
    summary_id         text NOT NULL,
    based_on_seq       bigint NOT NULL,
    content            text NOT NULL,
    content_hash       text NOT NULL,
    model_ref          text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, session_id, summary_id),
    UNIQUE (tenant_id, session_id, based_on_seq),
    FOREIGN KEY (tenant_id, session_id) REFERENCES session(tenant_id, session_id)
);

CREATE TABLE memory (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    memory_id          text NOT NULL,
    session_id         text,
    subject_id         text,
    memory_type        text NOT NULL,
    content            text,
    encrypted_content_ref text,
    content_hash       text NOT NULL,
    acl                 jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_event_id    text,
    version            bigint NOT NULL DEFAULT 1,
    expires_at         timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, memory_id),
    FOREIGN KEY (tenant_id, session_id) REFERENCES session(tenant_id, session_id),
    CHECK ((content IS NOT NULL) <> (encrypted_content_ref IS NOT NULL))
);

CREATE INDEX memory_subject_idx ON memory (tenant_id, subject_id, updated_at DESC);

CREATE TABLE memory_projection (
    tenant_id          text NOT NULL,
    memory_id          text NOT NULL,
    target_id          text NOT NULL,
    requested_version  bigint NOT NULL,
    projected_version  bigint,
    status             text NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending', 'processing', 'ready', 'failed')),
    last_error_code    text,
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, memory_id, target_id),
    FOREIGN KEY (tenant_id, memory_id) REFERENCES memory(tenant_id, memory_id)
);

CREATE TABLE knowledge_document (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    document_id        text NOT NULL,
    knowledge_base_id  text NOT NULL,
    object_uri         text NOT NULL,
    -- Small, operator-submitted text documents are stored canonically so the
    -- worker can project and retrieve them without trusting an arbitrary URI.
    -- An empty value remains valid for legacy object-backed rows.
    content            text NOT NULL DEFAULT '' CHECK (char_length(content) <= 200000),
    checksum           text NOT NULL,
    acl                 jsonb NOT NULL DEFAULT '{}'::jsonb,
    version            bigint NOT NULL DEFAULT 1,
    index_status       text NOT NULL DEFAULT 'pending',
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, document_id),
    UNIQUE (tenant_id, knowledge_base_id, checksum)
);

CREATE TABLE artifact (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    artifact_id        text NOT NULL,
    session_id         text,
    object_uri         text NOT NULL,
    media_type         text NOT NULL,
    byte_size          bigint NOT NULL CHECK (byte_size >= 0),
    checksum           text NOT NULL,
    encryption_key_ref text,
    scan_status        text NOT NULL DEFAULT 'pending'
                         CHECK (scan_status IN ('pending', 'clean', 'quarantined', 'failed')),
    retention_until    timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, artifact_id),
    FOREIGN KEY (tenant_id, session_id) REFERENCES session(tenant_id, session_id),
    UNIQUE (tenant_id, object_uri)
);

CREATE TABLE inbox (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    inbox_id            text NOT NULL,
    channel_binding_id text NOT NULL,
    agent_id            text NOT NULL,
    config_version      bigint NOT NULL,
    subject_id          text,
    idempotency_key    text NOT NULL,
    external_message_id text,
    session_id         text NOT NULL,
    status             text NOT NULL CHECK (status IN (
                           'received', 'queued', 'claimed', 'committed', 'reply_pending',
                           'delivered', 'retryable', 'unknown', 'failed'
                       )),
    execution_id       text,
    execution_attempt  integer NOT NULL DEFAULT 0 CHECK (execution_attempt >= 0),
    claimed_lease_fence bigint,
    claimed_routing_epoch bigint,
    claimed_security_epoch bigint,
    request_id         text NOT NULL,
    trace_id           text NOT NULL,
    payload_hash       text NOT NULL,
    payload            jsonb NOT NULL,
    received_at        timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, inbox_id),
    UNIQUE (tenant_id, idempotency_key),
    UNIQUE (tenant_id, execution_id),
    UNIQUE (tenant_id, inbox_id, execution_id),
    FOREIGN KEY (tenant_id, channel_binding_id) REFERENCES channel_binding(tenant_id, binding_id),
    FOREIGN KEY (tenant_id, agent_id) REFERENCES agent_app(tenant_id, agent_id),
    FOREIGN KEY (tenant_id, agent_id, config_version)
        REFERENCES agent_release(tenant_id, agent_id, config_version)
);

CREATE INDEX inbox_status_idx ON inbox (tenant_id, status, updated_at);

ALTER TABLE session
    ADD CONSTRAINT session_active_inbox_fk
    FOREIGN KEY (tenant_id, active_inbox_id) REFERENCES inbox(tenant_id, inbox_id);

CREATE TABLE outbox (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    outbox_id          text NOT NULL,
    aggregate_type     text NOT NULL,
    aggregate_id       text NOT NULL,
    inbox_id           text,
    event_type         text NOT NULL,
    payload            jsonb NOT NULL,
    idempotency_key    text NOT NULL,
    trace_id           text NOT NULL,
    status             text NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending', 'processing', 'published', 'delivered', 'unknown', 'dead')),
    attempts           integer NOT NULL DEFAULT 0,
    lease_owner        text,
    lease_expires_at   timestamptz,
    available_at       timestamptz NOT NULL DEFAULT now(),
    created_at         timestamptz NOT NULL DEFAULT now(),
    published_at       timestamptz,
    delivered_at       timestamptz,
    PRIMARY KEY (tenant_id, outbox_id),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, inbox_id) REFERENCES inbox(tenant_id, inbox_id),
    CHECK (
        (
            event_type = 'inbound.dispatch'
            AND aggregate_type = 'inbox'
            AND inbox_id IS NOT NULL
            AND aggregate_id = inbox_id
        )
        OR event_type <> 'inbound.dispatch'
    )
);

CREATE INDEX outbox_dispatch_idx
    ON outbox (status, available_at) WHERE status IN ('pending', 'processing');

CREATE TABLE execution_attempt (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    execution_id       text NOT NULL,
    attempt_no         integer NOT NULL CHECK (attempt_no > 0),
    inbox_id           text NOT NULL,
    session_id         text NOT NULL,
    worker_id          text NOT NULL,
    lease_fence        bigint NOT NULL,
    routing_epoch      bigint NOT NULL,
    security_epoch     bigint NOT NULL,
    status             text NOT NULL CHECK (status IN ('claimed', 'running', 'committed', 'lost_fence', 'cancelled', 'failed')),
    lease_expires_at   timestamptz NOT NULL,
    claimed_at         timestamptz NOT NULL DEFAULT now(),
    finished_at        timestamptz,
    PRIMARY KEY (tenant_id, execution_id, attempt_no),
    FOREIGN KEY (tenant_id, inbox_id, execution_id)
        REFERENCES inbox(tenant_id, inbox_id, execution_id),
    FOREIGN KEY (tenant_id, session_id) REFERENCES session(tenant_id, session_id),
    UNIQUE (tenant_id, inbox_id, attempt_no)
);

CREATE INDEX execution_attempt_lease_idx
    ON execution_attempt (status, lease_expires_at)
    WHERE status IN ('claimed', 'running');

CREATE TABLE budget_account (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    budget_name        text NOT NULL,
    unit               text NOT NULL CHECK (unit IN ('cost_micros', 'tokens', 'tool_units')),
    period_start       timestamptz NOT NULL,
    period_end         timestamptz NOT NULL,
    limit_units        bigint NOT NULL CHECK (limit_units >= 0),
    reserved_units     bigint NOT NULL DEFAULT 0 CHECK (reserved_units >= 0),
    spent_units        bigint NOT NULL DEFAULT 0 CHECK (spent_units >= 0),
    version            bigint NOT NULL DEFAULT 0,
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, budget_name, period_start),
    CHECK (period_end > period_start),
    CHECK (reserved_units + spent_units <= limit_units)
);

CREATE TABLE budget_reservation (
    tenant_id          text NOT NULL,
    reservation_id    text NOT NULL,
    budget_name        text NOT NULL,
    period_start       timestamptz NOT NULL,
    execution_id       text NOT NULL,
    estimated_units    bigint NOT NULL CHECK (estimated_units >= 0),
    actual_units       bigint CHECK (actual_units >= 0),
    status             text NOT NULL CHECK (status IN ('reserved', 'settled', 'released', 'expired', 'unknown')),
    expires_at         timestamptz NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT now(),
    settled_at         timestamptz,
    PRIMARY KEY (tenant_id, reservation_id),
    UNIQUE (tenant_id, execution_id, budget_name, period_start),
    FOREIGN KEY (tenant_id, execution_id) REFERENCES inbox(tenant_id, execution_id),
    FOREIGN KEY (tenant_id, budget_name, period_start)
        REFERENCES budget_account(tenant_id, budget_name, period_start)
);

CREATE INDEX budget_reservation_expiry_idx
    ON budget_reservation (status, expires_at)
    WHERE status IN ('reserved', 'unknown');

CREATE TABLE tool_execution (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    tool_call_id       text NOT NULL,
    inbox_id           text NOT NULL,
    execution_id       text NOT NULL,
    session_id         text NOT NULL,
    tool_step          integer NOT NULL CHECK (tool_step >= 0),
    tool_name          text NOT NULL,
    arguments_hash     text NOT NULL,
    retry_capability   text NOT NULL CHECK (retry_capability IN ('idempotent', 'queryable', 'non_retriable')),
    provider_idempotency_key text,
    provider_operation_id text,
    lease_fence        bigint NOT NULL,
    routing_epoch      bigint NOT NULL,
    security_epoch     bigint NOT NULL,
    status             text NOT NULL CHECK (status IN (
                           'prepared', 'confirmed', 'running', 'succeeded', 'failed',
                           'unknown', 'reconciling', 'manual_review', 'compensating', 'compensated'
                       )),
    result_ref         text,
    last_error_code    text,
    resolved_by        text,
    trace_id           text NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, tool_call_id),
    FOREIGN KEY (tenant_id, inbox_id, execution_id)
        REFERENCES inbox(tenant_id, inbox_id, execution_id),
    FOREIGN KEY (tenant_id, session_id) REFERENCES session(tenant_id, session_id),
    UNIQUE (tenant_id, execution_id, tool_step),
    CHECK (
        (retry_capability = 'idempotent' AND provider_idempotency_key IS NOT NULL)
        OR retry_capability <> 'idempotent'
    )
);

CREATE TABLE delivery_attempt (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    delivery_id        text NOT NULL,
    attempt_no         integer NOT NULL CHECK (attempt_no > 0),
    outbox_id          text NOT NULL,
    session_id         text NOT NULL,
    channel_binding_id text NOT NULL,
    retry_capability   text NOT NULL CHECK (retry_capability IN ('idempotent', 'queryable', 'non_retriable')),
    provider_idempotency_key text,
    provider_message_id text,
    request_hash       text NOT NULL,
    status             text NOT NULL CHECK (status IN ('prepared', 'sending', 'accepted', 'failed', 'unknown', 'reconciling', 'manual_review')),
    last_error_code    text,
    trace_id           text NOT NULL,
    started_at         timestamptz NOT NULL DEFAULT now(),
    finished_at        timestamptz,
    PRIMARY KEY (tenant_id, delivery_id, attempt_no),
    FOREIGN KEY (tenant_id, outbox_id) REFERENCES outbox(tenant_id, outbox_id),
    FOREIGN KEY (tenant_id, session_id) REFERENCES session(tenant_id, session_id),
    FOREIGN KEY (tenant_id, channel_binding_id) REFERENCES channel_binding(tenant_id, binding_id),
    CHECK (
        (retry_capability = 'idempotent' AND provider_idempotency_key IS NOT NULL)
        OR retry_capability <> 'idempotent'
    )
);

CREATE TABLE audit_log (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    audit_id           text NOT NULL,
    occurred_at        timestamptz NOT NULL DEFAULT now(),
    channel            text,
    subject_id         text,
    session_id         text,
    agent_name         text,
    tool_name          text,
    decision           text NOT NULL,
    reason_code        text,
    policy_version     text,
    latency_ms         integer,
    error_type         text,
    input_hash         text,
    output_hash        text,
    token_in           integer,
    token_out          integer,
    cost_micros        bigint,
    trace_id           text NOT NULL,
    request_id         text NOT NULL,
    encrypted_detail_ref text,
    PRIMARY KEY (tenant_id, audit_id, occurred_at)
) PARTITION BY RANGE (occurred_at);

-- A default partition keeps audit writes durable before a month-specific
-- partition is created by operations automation.  It can later be detached and
-- repartitioned without losing the parent-table RLS policy.
CREATE TABLE audit_log_default PARTITION OF audit_log DEFAULT;

-- Create audit_log partitions ahead of time in deployment migrations, for example:
-- CREATE TABLE audit_log_2026_09 PARTITION OF audit_log
-- FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');

CREATE INDEX audit_trace_idx ON audit_log (tenant_id, trace_id, occurred_at DESC);

-- ``audit_log`` is partitioned by timestamp, so PostgreSQL requires its
-- primary key to include ``occurred_at``.  This compact, unpartitioned gate
-- makes a deterministic at-least-once audit fact append exactly once without
-- granting workers read access to the audit ledger.
CREATE TABLE audit_dedup (
    tenant_id          text NOT NULL REFERENCES tenant(tenant_id),
    audit_id           text NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, audit_id)
);
