apiVersion: v1
kind: Service
metadata:
  name: trpc-backlog-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trpc-backlog-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trpc-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trpc-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trpc-admin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trpc-admin
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
