"""initial reliability schema

Revision ID: 0001
Revises:
Create Date: 2026-08-29 02:06:47.342067
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("audit_id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("agent_name", sa.String(length=128), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=True),
        sa.Column("decision", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("cost_micros", sa.BigInteger(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("invocation_id", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource", sa.String(length=256), nullable=False),
        sa.Column("config_revision", sa.Integer(), nullable=False),
        sa.Column("policy_revision", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index("ix_audit_tenant_time", ["tenant_id", "created_at"], unique=False)
        batch_op.create_index("ix_audit_trace", ["trace_id"], unique=False)

    op.create_table(
        "tenant",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("active_config_revision", sa.Integer(), nullable=True),
        sa.Column("audit_policy", sa.JSON(), nullable=False),
        sa.Column("budget_policy", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'disabled')", name="ck_tenant_status"
        ),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    with op.batch_alter_table("tenant", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenant_status"), ["status"], unique=False)

    op.create_table(
        "agent_app",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("app_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("agent_name", sa.String(length=128), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("model_config", sa.JSON(), nullable=False),
        sa.Column("tool_policy", sa.JSON(), nullable=False),
        sa.Column("storage_config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'disabled', 'superseded')", name="ck_agent_app_status"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("tenant_id", "app_id", "revision"),
    )
    with op.batch_alter_table("agent_app", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_app_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "artifact",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("artifact_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("object_ref", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "artifact_id", "version"),
    )
    with op.batch_alter_table("artifact", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifact_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "knowledge_document",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("object_ref", sa.Text(), nullable=False),
        sa.Column("indexed_version", sa.BigInteger(), nullable=False),
        sa.Column("tombstone", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "document_id", "version"),
    )
    with op.batch_alter_table("knowledge_document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_knowledge_document_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "tenant_config_revision",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'superseded')",
            name="ck_tenant_config_revision_status",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("tenant_id", "revision"),
    )
    with op.batch_alter_table("tenant_config_revision", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tenant_config_revision_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "channel_binding",
        sa.Column("binding_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("app_id", sa.String(length=64), nullable=False),
        sa.Column("app_revision", sa.Integer(), nullable=False),
        sa.Column("config_revision", sa.Integer(), nullable=False),
        sa.Column("channel_type", sa.String(length=32), nullable=False),
        sa.Column("external_account_id", sa.String(length=256), nullable=False),
        sa.Column("callback_path", sa.String(length=256), nullable=False),
        sa.Column("public_callback_id", sa.String(length=128), nullable=False),
        sa.Column("route_rule", sa.JSON(), nullable=False),
        sa.Column("secret_refs", sa.JSON(), nullable=False),
        sa.Column("identity_policy", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'disabled', 'revoked')", name="ck_channel_binding_status"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "app_id", "app_revision"],
            ["agent_app.tenant_id", "agent_app.app_id", "agent_app.revision"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("binding_id"),
        sa.UniqueConstraint("callback_path"),
        sa.UniqueConstraint("channel_type", "external_account_id"),
        sa.UniqueConstraint("public_callback_id"),
        sa.UniqueConstraint("tenant_id", "binding_id"),
    )
    with op.batch_alter_table("channel_binding", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_channel_binding_channel_type"), ["channel_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_channel_binding_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_channel_binding_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "scoped_state",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("app_id", sa.String(length=64), nullable=False),
        sa.Column("app_revision", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("subject_id", sa.String(length=256), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("scope IN ('app', 'user')", name="ck_scoped_state_scope"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "app_id", "app_revision"],
            ["agent_app.tenant_id", "agent_app.app_id", "agent_app.revision"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "app_id", "scope", "subject_id"),
    )
    op.create_table(
        "session",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("app_id", sa.String(length=64), nullable=False),
        sa.Column("app_revision", sa.Integer(), nullable=False),
        sa.Column("binding_id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("principal_id", sa.String(length=256), nullable=False),
        sa.Column("next_inbox_seq", sa.BigInteger(), nullable=False),
        sa.Column("log_version", sa.BigInteger(), nullable=False),
        sa.Column("state_version", sa.BigInteger(), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scope IN ('private', 'group', 'group_member')", name="ck_session_scope"
        ),
        sa.CheckConstraint("state_version <= log_version", name="ck_session_state_watermark"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "app_id", "app_revision"],
            ["agent_app.tenant_id", "agent_app.app_id", "agent_app.revision"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "binding_id"],
            ["channel_binding.tenant_id", "channel_binding.binding_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "session_id"),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_app_id"), ["app_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_session_binding_id"), ["binding_id"], unique=False)
        batch_op.create_index("ix_session_lease", ["lease_expires_at", "lease_owner"], unique=False)
        batch_op.create_index(batch_op.f("ix_session_principal_id"), ["principal_id"], unique=False)

    op.create_table(
        "inbox_message",
        sa.Column("inbox_id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("binding_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("accepted_seq", sa.BigInteger(), nullable=False),
        sa.Column("external_delivery_id", sa.String(length=256), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("claim_fencing_token", sa.BigInteger(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "status IN ('received', 'running', 'succeeded', 'retry_wait', 'dead_letter', 'reconcile')",
            name="ck_inbox_status",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "binding_id"],
            ["channel_binding.tenant_id", "channel_binding.binding_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["session.tenant_id", "session.session_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("inbox_id"),
        sa.UniqueConstraint("tenant_id", "binding_id", "external_delivery_id"),
        sa.UniqueConstraint("tenant_id", "inbox_id"),
        sa.UniqueConstraint("tenant_id", "session_id", "accepted_seq"),
    )
    with op.batch_alter_table("inbox_message", schema=None) as batch_op:
        batch_op.create_index("ix_inbox_dispatch", ["status", "received_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_inbox_message_binding_id"), ["binding_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inbox_message_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inbox_message_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_inbox_message_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_inbox_message_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inbox_message_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "memory_record",
        sa.Column("memory_id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("principal_id", sa.String(length=256), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("source_event_id", sa.String(length=128), nullable=False),
        sa.Column("extractor_version", sa.String(length=64), nullable=False),
        sa.Column("record_version", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["session.tenant_id", "session.session_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("memory_id"),
        sa.UniqueConstraint("tenant_id", "source_event_id", "extractor_version"),
    )
    with op.batch_alter_table("memory_record", schema=None) as batch_op:
        batch_op.create_index(
            "ix_memory_query", ["tenant_id", "principal_id", "record_version"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_record_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "session_summary",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("through_seq", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summarizer_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["session.tenant_id", "session.session_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "session_id"),
    )
    op.create_table(
        "agent_run",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("inbox_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("invocation_id", sa.String(length=128), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("app_id", sa.String(length=64), nullable=False),
        sa.Column("app_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("claim_fencing_token", sa.BigInteger(), nullable=True),
        sa.Column("start_version", sa.BigInteger(), nullable=False),
        sa.Column("last_seq", sa.BigInteger(), nullable=False),
        sa.Column("final_event_id", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'retry_wait', 'failed_final', 'reconcile')",
            name="ck_agent_run_status",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "app_id", "app_revision"],
            ["agent_app.tenant_id", "agent_app.app_id", "agent_app.revision"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "inbox_id"],
            ["inbox_message.tenant_id", "inbox_message.inbox_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["session.tenant_id", "session.session_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint("tenant_id", "inbox_id"),
        sa.UniqueConstraint("tenant_id", "request_id"),
        sa.UniqueConstraint("tenant_id", "run_id"),
    )
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_run_inbox_id"), ["inbox_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_run_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_run_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_run_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_run_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "channel_reply_credential",
        sa.Column("credential_id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("inbox_id", sa.String(length=32), nullable=False),
        sa.Column("credential_kind", sa.String(length=32), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("ciphertext_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'consumed', 'expired', 'unknown')",
            name="ck_channel_reply_credential_status",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "inbox_id"],
            ["inbox_message.tenant_id", "inbox_message.inbox_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("credential_id"),
        sa.UniqueConstraint("tenant_id", "inbox_id", "credential_kind"),
    )
    with op.batch_alter_table("channel_reply_credential", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_channel_reply_credential_inbox_id"), ["inbox_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_channel_reply_credential_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_channel_reply_credential_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "reply_outbox",
        sa.Column("outbox_id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("binding_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("reply_id", sa.String(length=128), nullable=False),
        sa.Column("part_no", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_token", sa.String(length=64), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_type", sa.String(length=128), nullable=True),
        sa.Column("external_message_id", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'sending', 'sent', 'retry_wait', 'dead_letter', 'unknown')",
            name="ck_outbox_status",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "binding_id"],
            ["channel_binding.tenant_id", "channel_binding.binding_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "run_id"],
            ["agent_run.tenant_id", "agent_run.run_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["session.tenant_id", "session.session_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("outbox_id"),
        sa.UniqueConstraint("tenant_id", "reply_id", "part_no"),
    )
    with op.batch_alter_table("reply_outbox", schema=None) as batch_op:
        batch_op.create_index("ix_outbox_claim", ["status", "next_retry_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reply_outbox_binding_id"), ["binding_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_reply_outbox_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reply_outbox_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_reply_outbox_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_reply_outbox_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "session_event",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("event_key", sa.String(length=256), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=True),
        sa.Column("content_ref", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("state_delta", sa.JSON(), nullable=False),
        sa.Column("framework_event_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "visibility IN ('staged', 'committed', 'aborted')", name="ck_event_visibility"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "run_id"],
            ["agent_run.tenant_id", "agent_run.run_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["session.tenant_id", "session.session_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "event_id"),
        sa.UniqueConstraint("tenant_id", "run_id", "event_key"),
        sa.UniqueConstraint("tenant_id", "session_id", "seq"),
    )
    with op.batch_alter_table("session_event", schema=None) as batch_op:
        batch_op.create_index(
            "ix_session_event_replay", ["tenant_id", "session_id", "seq"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_session_event_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_session_event_visibility"), ["visibility"], unique=False
        )

    op.create_table(
        "tool_effect",
        sa.Column("effect_id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("tool_version", sa.String(length=64), nullable=False),
        sa.Column("effect_class", sa.String(length=32), nullable=False),
        sa.Column("args_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("execution_token", sa.String(length=64), nullable=False),
        sa.Column("execution_owner", sa.String(length=128), nullable=True),
        sa.Column("execution_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("downstream_key", sa.String(length=256), nullable=True),
        sa.Column("downstream_id", sa.String(length=256), nullable=True),
        sa.Column("result_hash", sa.String(length=64), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result_ref", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('reserved', 'executing', 'succeeded', 'retry_wait', 'failed_final', 'unknown')",
            name="ck_tool_effect_status",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "run_id"],
            ["agent_run.tenant_id", "agent_run.run_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["session.tenant_id", "session.session_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("effect_id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key"),
    )
    with op.batch_alter_table("tool_effect", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tool_effect_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_effect_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_effect_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_effect_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tool_effect", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tool_effect_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_tool_effect_status"))
        batch_op.drop_index(batch_op.f("ix_tool_effect_session_id"))
        batch_op.drop_index(batch_op.f("ix_tool_effect_run_id"))

    op.drop_table("tool_effect")
    with op.batch_alter_table("session_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_event_visibility"))
        batch_op.drop_index(batch_op.f("ix_session_event_run_id"))
        batch_op.drop_index("ix_session_event_replay")

    op.drop_table("session_event")
    with op.batch_alter_table("reply_outbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reply_outbox_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_reply_outbox_status"))
        batch_op.drop_index(batch_op.f("ix_reply_outbox_session_id"))
        batch_op.drop_index(batch_op.f("ix_reply_outbox_run_id"))
        batch_op.drop_index(batch_op.f("ix_reply_outbox_binding_id"))
        batch_op.drop_index("ix_outbox_claim")

    op.drop_table("reply_outbox")
    with op.batch_alter_table("channel_reply_credential", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_reply_credential_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_channel_reply_credential_status"))
        batch_op.drop_index(batch_op.f("ix_channel_reply_credential_inbox_id"))

    op.drop_table("channel_reply_credential")
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_run_trace_id"))
        batch_op.drop_index(batch_op.f("ix_agent_run_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_agent_run_status"))
        batch_op.drop_index(batch_op.f("ix_agent_run_session_id"))
        batch_op.drop_index(batch_op.f("ix_agent_run_inbox_id"))

    op.drop_table("agent_run")
    op.drop_table("session_summary")
    with op.batch_alter_table("memory_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_record_tenant_id"))
        batch_op.drop_index("ix_memory_query")

    op.drop_table("memory_record")
    with op.batch_alter_table("inbox_message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inbox_message_trace_id"))
        batch_op.drop_index(batch_op.f("ix_inbox_message_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_inbox_message_status"))
        batch_op.drop_index(batch_op.f("ix_inbox_message_session_id"))
        batch_op.drop_index(batch_op.f("ix_inbox_message_request_id"))
        batch_op.drop_index(batch_op.f("ix_inbox_message_binding_id"))
        batch_op.drop_index("ix_inbox_dispatch")

    op.drop_table("inbox_message")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_principal_id"))
        batch_op.drop_index("ix_session_lease")
        batch_op.drop_index(batch_op.f("ix_session_binding_id"))
        batch_op.drop_index(batch_op.f("ix_session_app_id"))

    op.drop_table("session")
    op.drop_table("scoped_state")
    with op.batch_alter_table("channel_binding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_binding_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_channel_binding_status"))
        batch_op.drop_index(batch_op.f("ix_channel_binding_channel_type"))

    op.drop_table("channel_binding")
    with op.batch_alter_table("tenant_config_revision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_config_revision_tenant_id"))

    op.drop_table("tenant_config_revision")
    with op.batch_alter_table("knowledge_document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_document_tenant_id"))

    op.drop_table("knowledge_document")
    with op.batch_alter_table("artifact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifact_tenant_id"))

    op.drop_table("artifact")
    with op.batch_alter_table("agent_app", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_app_tenant_id"))

    op.drop_table("agent_app")
    with op.batch_alter_table("tenant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_status"))

    op.drop_table("tenant")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_trace")
        batch_op.drop_index("ix_audit_tenant_time")
        batch_op.drop_index(batch_op.f("ix_audit_log_tenant_id"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
