"""public channel ingress route

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-29 02:24:49.337481
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_ingress_route",
        sa.Column("public_callback_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("binding_id", sa.String(length=64), nullable=False),
        sa.Column("channel_type", sa.String(length=32), nullable=False),
        sa.Column("config_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'disabled', 'revoked')", name="ck_channel_ingress_route_status"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "binding_id"],
            ["channel_binding.tenant_id", "channel_binding.binding_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("public_callback_id"),
        sa.UniqueConstraint("binding_id"),
    )
    with op.batch_alter_table("channel_ingress_route", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_channel_ingress_route_channel_type"), ["channel_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_channel_ingress_route_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_channel_ingress_route_tenant_id"), ["tenant_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel_ingress_route", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_ingress_route_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_channel_ingress_route_status"))
        batch_op.drop_index(batch_op.f("ix_channel_ingress_route_channel_type"))

    op.drop_table("channel_ingress_route")
    # ### end Alembic commands ###
