"""initial tenant platform schema

Revision ID: 1dc9c6ba78b8
Revises:
Create Date: 2026-08-25 21:40:04.638935
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1dc9c6ba78b8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("artifact_id", sa.String(length=80), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_uri", sa.String(length=2048), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_blob", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "artifact_id"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("audit_id", sa.String(length=80), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=80), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("agent_name", sa.String(length=63), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=True),
        sa.Column("decision", sa.String(length=64), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("token_input", sa.BigInteger(), nullable=False),
        sa.Column("token_output", sa.BigInteger(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=255), nullable=True),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "audit_id"),
    )
    op.create_index("ix_audit_tenant_occurred", "audit_logs", ["tenant_id", "occurred_at"], unique=False)
    op.create_index("ix_audit_trace", "audit_logs", ["trace_id"], unique=False)
    op.create_table(
        "inbound_receipts",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "dedupe_key"),
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("document_id", sa.String(length=255), nullable=False),
        sa.Column("chunk_id", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding_json", sa.JSON(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("embedding_model", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "document_id", "chunk_id"),
    )
    op.create_table(
        "memories",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("user_id", sa.String(length=80), nullable=False),
        sa.Column("memory_id", sa.String(length=80), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "user_id", "memory_id"),
    )
    op.create_index(
        "ix_memory_tenant_user_updated", "memories", ["tenant_id", "user_id", "updated_at"], unique=False
    )
    op.create_table(
        "outbox",
        sa.Column("outbox_id", sa.String(length=80), nullable=False),
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("last_error_type", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("outbox_id"),
    )
    op.create_index("ix_outbox_ready", "outbox", ["status", "available_at"], unique=False)
    op.create_table(
        "session_leases",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "session_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("app_id", sa.String(length=63), nullable=False),
        sa.Column("user_id", sa.String(length=80), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("state_json", sa.JSON(), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("last_event_sequence", sa.BigInteger(), nullable=False),
        sa.Column("summary_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "session_id"),
    )
    op.create_index(
        "ix_sessions_tenant_user_updated", "sessions", ["tenant_id", "user_id", "updated_at"], unique=False
    )
    op.create_table(
        "summaries",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("through_event_sequence", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "session_id"),
    )
    op.create_table(
        "tenant_concurrency_slots",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "owner"),
    )
    op.create_index(
        "ix_tenant_concurrency_expiry",
        "tenant_concurrency_slots",
        ["tenant_id", "lease_expires_at"],
        unique=False,
    )
    op.create_table(
        "tenant_usage",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "period"),
    )
    op.create_table(
        "tenants",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("active_config_revision", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "agent_apps",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("app_id", sa.String(length=63), nullable=False),
        sa.Column("agent_name", sa.String(length=63), nullable=False),
        sa.Column("config_revision", sa.Integer(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "app_id"),
    )
    op.create_table(
        "identity_links",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("external_user_id_hash", sa.String(length=64), nullable=False),
        sa.Column("canonical_user_id", sa.String(length=80), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "channel", "external_user_id_hash"),
    )
    op.create_table(
        "session_events",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("event_id", sa.String(length=80), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("state_delta_json", sa.JSON(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"], ["sessions.tenant_id", "sessions.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "event_id"),
        sa.UniqueConstraint("tenant_id", "session_id", "sequence", name="uq_session_event_sequence"),
    )
    op.create_index(
        "ix_events_tenant_session_sequence",
        "session_events",
        ["tenant_id", "session_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "tenant_config_versions",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "revision"),
        sa.UniqueConstraint("tenant_id", "checksum_sha256", name="uq_config_checksum"),
    )
    op.create_table(
        "channel_bindings",
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("binding_id", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("app_id", sa.String(length=63), nullable=False),
        sa.Column("external_account_id", sa.String(length=255), nullable=False),
        sa.Column("config_revision", sa.Integer(), nullable=False),
        sa.Column("credential_refs_json", sa.JSON(), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "app_id"],
            ["agent_apps.tenant_id", "agent_apps.app_id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "binding_id"),
        sa.UniqueConstraint("channel", "binding_id", name="uq_channel_binding_route"),
        sa.UniqueConstraint("tenant_id", "channel", "external_account_id", name="uq_tenant_channel_account"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("channel_bindings")
    op.drop_table("tenant_config_versions")
    op.drop_index("ix_events_tenant_session_sequence", table_name="session_events")
    op.drop_table("session_events")
    op.drop_table("identity_links")
    op.drop_table("agent_apps")
    op.drop_table("tenants")
    op.drop_table("tenant_usage")
    op.drop_index("ix_tenant_concurrency_expiry", table_name="tenant_concurrency_slots")
    op.drop_table("tenant_concurrency_slots")
    op.drop_table("summaries")
    op.drop_index("ix_sessions_tenant_user_updated", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("session_leases")
    op.drop_index("ix_outbox_ready", table_name="outbox")
    op.drop_table("outbox")
    op.drop_index("ix_memory_tenant_user_updated", table_name="memories")
    op.drop_table("memories")
    op.drop_table("knowledge_chunks")
    op.drop_table("inbound_receipts")
    op.drop_index("ix_audit_trace", table_name="audit_logs")
    op.drop_index("ix_audit_tenant_occurred", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
