apiVersion: apps/v1
kind: Deployment
metadata:
  name: trpc-worker
spec:
  template:
    spec:
      containers:
        - name: worker
          volumeMounts:
            - name: model-secrets
              mountPath: /run/secrets/model_api_key
              subPath: model_api_key
              readOnly: true
      volumes:
        - name: model-secrets
          secret:
            secretName: trpc-model-secrets
            defaultMode: 288
