"""Explicit, tenant-aware adapters for replaceable projection backends."""

from trpc_service.backends.contracts import (
    ArtifactBackend,
    ArtifactObject,
    BackendConflictError,
    BackendCorruptionError,
    BackendError,
    BackendRole,
    ConsistencyMetadata,
    DurabilityClass,
    KnowledgeBackend,
    KnowledgeDocument,
    MemoryBackend,
    MemoryProjection,
    ReadVisibility,
    ScopedStateBackend,
    ScopedStateProjection,
    SessionProjection,
    SessionProjectionBackend,
    SummaryBackend,
    SummaryProjection,
    WatermarkRegressionError,
    WriteDisposition,
    WriteResult,
    canonical_json_hash,
)
from trpc_service.backends.inmemory import InMemoryBackend
from trpc_service.backends.migration import (
    InMemoryMigrationStatusBackend,
    MigrationPhase,
    MigrationPlan,
    MigrationStateError,
    MigrationStatus,
    MigrationStatusBackend,
    SessionShadowMigrator,
    ShadowComparison,
)
from trpc_service.backends.redis_session import (
    REDIS_SESSION_CAS_LUA,
    AsyncRedisSessionClient,
    RedisSessionProjectionBackend,
)
from trpc_service.backends.router import (
    BackendMode,
    BackendNotRegisteredError,
    BackendRouter,
    BackendRoutingError,
    TenantBackendBundle,
    UnsafeBackendError,
)

__all__ = [
    "REDIS_SESSION_CAS_LUA",
    "ArtifactBackend",
    "ArtifactObject",
    "AsyncRedisSessionClient",
    "BackendConflictError",
    "BackendCorruptionError",
    "BackendError",
    "BackendMode",
    "BackendNotRegisteredError",
    "BackendRole",
    "BackendRouter",
    "BackendRoutingError",
    "ConsistencyMetadata",
    "DurabilityClass",
    "InMemoryBackend",
    "InMemoryMigrationStatusBackend",
    "KnowledgeBackend",
    "KnowledgeDocument",
    "MemoryBackend",
    "MemoryProjection",
    "MigrationPhase",
    "MigrationPlan",
    "MigrationStateError",
    "MigrationStatus",
    "MigrationStatusBackend",
    "ReadVisibility",
    "RedisSessionProjectionBackend",
    "ScopedStateBackend",
    "ScopedStateProjection",
    "SessionProjection",
    "SessionProjectionBackend",
    "SessionShadowMigrator",
    "ShadowComparison",
    "SummaryBackend",
    "SummaryProjection",
    "TenantBackendBundle",
    "UnsafeBackendError",
    "WatermarkRegressionError",
    "WriteDisposition",
    "WriteResult",
    "canonical_json_hash",
]
