from __future__ import annotations

from datetime import UTC, datetime, timedelta

import pytest

from scripts.evidence_lineage import (
    DEFAULT_EVIDENCE_TTL_SECONDS,
    FINGERPRINT_MAX_BYTES,
    FINGERPRINT_MAX_FILES,
    SOURCE_FINGERPRINT_ROOTS,
    build_evidence,
    current_release_binding,
    runtime_fingerprint,
    source_fingerprint,
    validate_current_candidate_evidence,
    validate_release_binding,
)


def _runtime() -> dict[str, object]:
    return runtime_fingerprint(
        mode="real_postgresql_redis_multiprocess",
        worker_identities=[{"pid": 11, "container_id": "worker-a"}],
        stream="trpc:inbound:v1",
        group="trpc-workers-v1",
        parameters={"callbacks": 200, "burst_turns": 200},
    )


def test_shared_source_roots_include_dockerfile() -> None:
    assert "Dockerfile" in SOURCE_FINGERPRINT_ROOTS
    assert {".dockerignore", "alembic.ini", "README.md"} <= set(SOURCE_FINGERPRINT_ROOTS)
    assert "tests/integration" in SOURCE_FINGERPRINT_ROOTS


def test_source_fingerprint_is_bounded_and_excludes_generated_files(tmp_path) -> None:
    source = tmp_path / "source"
    cache = source / "__pycache__"
    cache.mkdir(parents=True)
    (source / "main.py").write_text("stable", encoding="utf-8")
    (cache / "main.pyc").write_bytes(b"generated")

    result = source_fingerprint(tmp_path, ("source",))

    assert result["status"] == "available"
    assert result["file_count"] == 1
    assert result["file_count_limit"] == FINGERPRINT_MAX_FILES
    assert result["byte_limit"] == FINGERPRINT_MAX_BYTES


def test_source_fingerprint_ignores_root_and_nested_cache_artifacts(tmp_path) -> None:
    (tmp_path / "app.py").write_text("APP = 1\n", encoding="utf-8")
    nested = tmp_path / "package" / "module.py"
    nested.parent.mkdir(parents=True)
    nested.write_text("MODULE = 1\n", encoding="utf-8")

    before = source_fingerprint(tmp_path, (".",))

    cache_directories = (
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".cache",
        "cache",
        "runs",
        "secrets",
        "package/__pycache__",
        "package/.mypy_cache",
        "package/nested/.pytest_cache",
        "package/nested/deep/.ruff_cache",
    )
    for relative_cache in cache_directories:
        cache = tmp_path / relative_cache
        cache.mkdir(parents=True)
        (cache / "generated.cache").write_bytes(b"generated cache data")

    (tmp_path / "module.pyc").write_bytes(b"generated bytecode")
    (tmp_path / "package" / "nested" / "module.pyo").write_bytes(b"generated bytecode")

    after = source_fingerprint(tmp_path, (".",))

    assert after["value"] == before["value"]
    assert after["file_count"] == before["file_count"]
    assert after["total_bytes"] == before["total_bytes"]


def test_source_fingerprint_does_not_follow_symlink_entries(tmp_path) -> None:
    source = tmp_path / "source"
    source.mkdir()
    (source / "main.py").write_text("VALUE = 1\n", encoding="utf-8")
    try:
        (source / "link.py").symlink_to(source / "main.py")
    except (OSError, NotImplementedError):
        pytest.skip("symlinks are unavailable in this test environment")

    result = source_fingerprint(tmp_path, ("source",))

    assert result["status"] == "available"
    assert result["file_count"] == 1


def test_source_fingerprint_changes_for_real_python_content(tmp_path) -> None:
    source = tmp_path / "source.py"
    source.write_text("VALUE = 1\n", encoding="utf-8")

    before = source_fingerprint(tmp_path, (".",))
    source.write_text("VALUE = 2\n", encoding="utf-8")
    after = source_fingerprint(tmp_path, (".",))

    assert after["value"] != before["value"]
    assert after["file_count"] == before["file_count"]
    assert after["total_bytes"] == before["total_bytes"]


def test_source_fingerprint_ignores_runtime_gate_config_but_tracks_source(
    tmp_path,
) -> None:
    deploy = tmp_path / "deploy"
    deploy.mkdir()
    runtime_configs = (deploy / "runtime-gate.yaml",)
    for runtime_config in runtime_configs:
        runtime_config.write_text("release_id: first\n", encoding="utf-8")
    source = tmp_path / "source.py"
    source.write_text("VALUE = 1\n", encoding="utf-8")

    before = source_fingerprint(tmp_path, (".",))
    for runtime_config in runtime_configs:
        runtime_config.write_text("release_id: second\n", encoding="utf-8")
    after_config_change = source_fingerprint(tmp_path, (".",))

    assert after_config_change["value"] == before["value"]
    assert after_config_change["file_count"] == before["file_count"]
    assert after_config_change["total_bytes"] == before["total_bytes"]

    source.write_text("VALUE = 2\n", encoding="utf-8")
    after_source_change = source_fingerprint(tmp_path, (".",))

    assert after_source_change["value"] != before["value"]


def test_current_candidate_evidence_has_versioned_safe_runtime_metadata(tmp_path) -> None:
    report = build_evidence(
        root=tmp_path,
        producer="tests.evidence_lineage",
        run_id="test-evidence-run",
        runtime=_runtime(),
        source_roots=(),
    )

    assert report["schema_version"] == 1
    assert report["kind"] == "current_candidate"
    assert report["producer"] == "tests.evidence_lineage"
    assert report["generated_at"].endswith("Z")
    assert report["run_id"] == "test-evidence-run"
    runtime = report["runtime_fingerprint"]
    assert runtime["status"] == "available"
    assert len(runtime["value"]) == 64
    serialized = str(report)
    assert "worker-a" not in serialized
    assert "trpc:inbound:v1" not in serialized
    assert "trpc-workers-v1" not in serialized


def test_runtime_fingerprint_is_unavailable_without_worker_runtime() -> None:
    result = runtime_fingerprint(
        mode="real_postgresql_redis_multiprocess",
        worker_identities=[],
        stream="stream",
        group="group",
        parameters={},
    )

    assert result == {
        "algorithm": "sha256",
        "status": "unavailable",
        "reason": "runtime_not_available",
    }


def test_evidence_validation_rejects_missing_stale_future_and_mismatched_lineage(
    tmp_path, monkeypatch
) -> None:
    monkeypatch.setenv("TRPC_RELEASE_ID", "release-evidence-test")
    monkeypatch.setenv("TRPC_RELEASE_NONCE", "r" * 32)
    current = source_fingerprint(tmp_path, ())
    now = datetime(2026, 8, 22, 12, 0, tzinfo=UTC)
    valid = build_evidence(
        root=tmp_path,
        producer="tests.evidence_lineage",
        run_id="valid-evidence-run",
        generated_at=now,
        runtime=_runtime(),
        source_roots=(),
    )

    assert validate_current_candidate_evidence(valid, current_source=current, now=now) == []
    assert validate_current_candidate_evidence({}, current_source=current, now=now)

    missing_nonce = dict(valid)
    missing_nonce.pop("run_nonce")
    assert (
        validate_current_candidate_evidence(missing_nonce, current_source=current, now=now)[0]
        == "production evidence run_nonce is missing or invalid"
    )

    stale = dict(valid)
    stale["generated_at"] = (now - timedelta(seconds=DEFAULT_EVIDENCE_TTL_SECONDS + 1)).isoformat()
    assert (
        "expired" in validate_current_candidate_evidence(stale, current_source=current, now=now)[0]
    )

    future = dict(valid)
    future["generated_at"] = (now + timedelta(seconds=1)).isoformat()
    assert (
        "future" in validate_current_candidate_evidence(future, current_source=current, now=now)[0]
    )

    mismatch = dict(valid)
    mismatch["source_fingerprint"] = {
        "algorithm": "sha256",
        "status": "available",
        "value": "0" * 64,
    }
    assert (
        "different candidate"
        in validate_current_candidate_evidence(mismatch, current_source=current, now=now)[0]
    )


def test_evidence_validation_rejects_unavailable_runtime(tmp_path) -> None:
    current = source_fingerprint(tmp_path, ())
    report = build_evidence(
        root=tmp_path,
        producer="tests.evidence_lineage",
        run_id="runtime-unavailable-run",
        runtime=None,
        source_roots=(),
    )

    reasons = validate_current_candidate_evidence(report, current_source=current)

    assert reasons == ["production evidence runtime fingerprint is unavailable"]


def test_release_binding_is_required_and_compared_without_exposing_nonce(
    tmp_path, monkeypatch
) -> None:
    monkeypatch.delenv("TRPC_RELEASE_ID", raising=False)
    monkeypatch.delenv("TRPC_RELEASE_NONCE", raising=False)
    current = source_fingerprint(tmp_path, ())
    evidence = build_evidence(
        root=tmp_path,
        producer="tests.evidence_lineage",
        runtime=_runtime(),
        source_roots=(),
    )

    assert validate_release_binding(evidence) == ["production evidence release_binding is missing"]
    with pytest.raises(ValueError, match="TRPC_RELEASE_ID and TRPC_RELEASE_NONCE"):
        current_release_binding(required=True)

    monkeypatch.setenv("TRPC_RELEASE_ID", "release-evidence-test")
    release_nonce = "r" * 32
    monkeypatch.setenv("TRPC_RELEASE_NONCE", release_nonce)
    expected = current_release_binding(required=True)
    assert expected is not None
    bound = build_evidence(
        root=tmp_path,
        producer="tests.evidence_lineage",
        runtime=_runtime(),
        source_roots=(),
    )
    assert validate_current_candidate_evidence(bound, current_source=current) == []
    assert release_nonce not in str(bound)

    mismatched = dict(bound)
    mismatched["release_binding"] = {
        "release_id": "release-other",
        "nonce_sha256": expected["nonce_sha256"],
    }
    assert validate_release_binding(mismatched, expected=expected) == [
        "production evidence release_id does not match expected release"
    ]
